### ISSUE TITLE
Meteor 1.3 compatibility

### ISSUE THREAD

**Issue by UnconditionedLife** [VeliovGroup/ostrio-neo4jdriver#37]
I continue to have problems with the 'Cannot find module fibers' error. I have tried both the -fiber and non-fiber versions of the driver and both cause Meteor not to load on my Mac OS X.  I'm starting to think that this package is not compatible with Meteor 1.3, is that correct? If so, when do you think when you might have a 1.3 compatible version?

Thanks in advance!
Добрый день

**Comment by HannesHolste** [comment]
Though @dr-dimitru hasn't updated this for 1.3, it still works for me. `Neo4j` is still treated as a global, rather than using the new import statements e.g. `import React from 'react';`

I had the fibers problem on OSX too, but I resolved it See my post at: https://github.com/VeliovGroup/ostrio-neo4jdriver/issues/26#issuecomment-172399951

**Comment by dr-dimitru** [comment]
Hi everyone, thank you for contribution. I'm really sorry, but I can't put my hands on it right now. Let me make this clear - update and all testing from my side will be made until end of first half of 2016.

@HannesHolste thank you for reply in this thread.
